# Site settings
title: Stata - jsonio
email: William.Buchanan@mpls.k12.mn.us
description: A JSON serializer for Stata using the Java-API and Jackson JSON.
baseurl: "/StataJSON" # Name of the repository
url: "https://wbuchanan.github.io" # the base hostname & protocol for your site
twitter_username: PACESconsulting
github_username:  wbuchanan

# Build settings
markdown: kramdown
kramdown:
  input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
